# config/packages/swiftmailer.yaml
swiftmailer:
    transport: gmail
    username: 'beeblyinfo@gmail.com'
    password: 'akewbucqjrfviqvr'
    host: 'smtp.gmail.com'
    port: 465
    encryption: ssl
    spool: { type: 'memory' }